name: Python-CI
run-name: ${{ github.actor }} triggering for ${{ github.sha }}
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
env:
  PythonVersion: 3.8
jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PythonVersion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PythonVersion }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt
          pip install flake8 coverage

      - name: Run coverage test
        run: coverage run ./src/manage.py test

      - name: Generate report
        run: coverage report

      - name: Lint with flake8
        run: flake8 ./src --show-source --statistics --exit-zero

      - name: Check Complexity
        run: flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Upload Python code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-code
          path: ./src